// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLT0BBKP4CwGf2biIjeh4a9glGSksgidA',
    appId: '1:117993267704:web:15046ca878247691bc760d',
    messagingSenderId: '117993267704',
    projectId: 'app-placeme',
    authDomain: 'app-placeme.firebaseapp.com',
    storageBucket: 'app-placeme.appspot.com',
    measurementId: 'G-K5115B2BTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOq26zea7n3G788ErS6_ws3Any1jug2WM',
    appId: '1:117993267704:android:a1b2b8fbaf83659cbc760d',
    messagingSenderId: '117993267704',
    projectId: 'app-placeme',
    storageBucket: 'app-placeme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsK8h0T-Y56Pxmr1JTqf81Xynfd-zAdnk',
    appId: '1:117993267704:ios:fe0954e3e325dbe7bc760d',
    messagingSenderId: '117993267704',
    projectId: 'app-placeme',
    storageBucket: 'app-placeme.appspot.com',
    iosBundleId: 'com.example.placeme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsK8h0T-Y56Pxmr1JTqf81Xynfd-zAdnk',
    appId: '1:117993267704:ios:fe0954e3e325dbe7bc760d',
    messagingSenderId: '117993267704',
    projectId: 'app-placeme',
    storageBucket: 'app-placeme.appspot.com',
    iosBundleId: 'com.example.placeme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLT0BBKP4CwGf2biIjeh4a9glGSksgidA',
    appId: '1:117993267704:web:0ea00274b526c215bc760d',
    messagingSenderId: '117993267704',
    projectId: 'app-placeme',
    authDomain: 'app-placeme.firebaseapp.com',
    storageBucket: 'app-placeme.appspot.com',
    measurementId: 'G-FV70BMMD5P',
  );

}